### ISSUE TITLE
Project Aborts with BadZipFile Error

### ISSUE THREAD

**Issue by bcoleman96** [monarch-initiative/yactp#1]
Project aborts when encountering bad zip file with the following code:

Parsing from  ct_data/celecoxib/NCT01555073.xml
Traceback (most recent call last):
  File "/home/bcoleman/Desktop/Projects/novelKinaseTargetSearch/yactp/run_parser.py", line 30, in <module>
    main()
  File "/home/bcoleman/Desktop/Projects/novelKinaseTargetSearch/yactp/run_parser.py", line 22, in main
    ctp.download_query_results(query=pki)
  File "/home/bcoleman/Desktop/Projects/novelKinaseTargetSearch/yactp/ctparser/ct_parser.py", line 49, in download_query_results
    with zipfile.ZipFile(save_path, 'r') as zip_ref:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Process finished with exit code 1

**Comment by pnrobinson** [comment]
We should probably wrap in a Try statement. But what file was causing the error? The Clinical Trials site should only be returning zip files afaik
