### ISSUE TITLE
ModuleNotFoundError: No module named 'ctparser.ct_study'

### ISSUE THREAD

**Issue by vidarmehr** [monarch-initiative/yactp#8]
@pnrobinson When I ran:
`parseCT.py -m mesh_D009369_12_06_2020.tsv`
I got this error message:
> Traceback (most recent call last):
  File "parseCT.py", line 3, in <module>
    from ctparser import CtStudy, CtStudyAggregator
  File "/Users/ravanv/PycharmProjects/yactp/ctparser/__init__.py", line 1, in <module>
    from .ct_parser import ClinicalTrialsParser
  File "/Users/ravanv/PycharmProjects/yactp/ctparser/ct_parser.py", line 6, in <module>
    from .ct_xml_parser import ClinicalTrialsXmlParser
  File "/Users/ravanv/PycharmProjects/yactp/ctparser/ct_xml_parser.py", line 2, in <module>
    from .ct_study import CtStudy
ModuleNotFoundError: No module named 'ctparser.ct_study'

**Comment by pnrobinson** [comment]
@vidarmehr  I am not sure it seems to work on my side, let's touch bases today
